---
- name: Test for raspberry pi /proc/cpuinfo
  command: grep -E "Raspberry Pi|BCM2708|BCM2709|BCM2835|BCM2836" /proc/cpuinfo
  register: raspberrypi_cpuinfo_grep
  failed_when: false
  changed_when: false

- name: Test for raspberry pi /proc/device-tree/model
  command: grep -E "Raspberry Pi" /proc/device-tree/model
  register: raspberrypi_device_tree_model_grep
  failed_when: false
  changed_when: false

- name: Set raspberrypi_is_raspberry_pi fact to true
  set_fact:
    raspberrypi_is_raspberry_pi: true
  when:
    raspberrypi_cpuinfo_grep.rc == 0 or raspberrypi_device_tree_model_grep.rc == 0

- name: Set raspberrypi_detected_distribution to Raspbian
  set_fact:
    raspberrypi_detected_distribution: Raspbian
  when: >
    raspberrypi_is_raspberry_pi|default(false) and
    ( ansible_facts.lsb.id|default("") == "Raspbian" or
      ansible_facts.lsb.description|default("") is match("[Rr]aspbian.*") )

- name: Set raspberrypi_detected_distribution to Raspbian (ARM64 on Debian Buster)
  set_fact:
    raspberrypi_detected_distribution: Raspbian
  when:
    - ansible_facts.architecture is search("aarch64")
    - raspberrypi_is_raspberry_pi|default(false)
    - ansible_facts.lsb.description|default("") is match("Debian.*buster")

- name: Set raspberrypi_detected_distribution_major_version
  set_fact:
    raspberrypi_detected_distribution_major_version: "{{ ansible_facts.lsb.major_release }}"
  when:
    - raspberrypi_detected_distribution | default("") == "Raspbian"

- name: Set raspberrypi_detected_distribution to Raspbian (ARM64 on Debian Bullseye)
  set_fact:
    raspberrypi_detected_distribution: Raspbian
  when:
    - ansible_facts.architecture is search("aarch64")
    - raspberrypi_is_raspberry_pi|default(false)
    - ansible_facts.lsb.description|default("") is match("Debian.*bullseye")

- name: Execute OS related tasks on the Raspberry Pi - {{ action_ }}
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ action_ }}/{{ raspberrypi_include_distribution }}-{{ raspberrypi_include_distribution_major_version }}.yml"
    - "{{ action_ }}/{{ raspberrypi_include_distribution }}.yml"
    - "{{ action_ }}/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ action_ }}/{{ ansible_distribution }}.yml"
    - "{{ action_ }}/default.yml"
  vars:
    action_: >-
      {% if raspberrypi_state == "present" %}setup{% else %}teardown{% endif %}
    raspberrypi_include_distribution: "{{ raspberrypi_detected_distribution | default(ansible_distribution) }}"
    raspberrypi_include_distribution_major_version: >-
      {{ raspberrypi_detected_distribution_major_version | default(ansible_distribution_major_version) }}
  when:
    - raspberrypi_is_raspberry_pi|default(false)
