- name: Add rancher helm repo
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: https://releases.rancher.com/server-charts/stable

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 10

- name: Create the cattle-system namespace for rancher
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: cattle-system
    state: present

- name: Deploy rancher with dns name {{ rancher_dns_name }}
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-stable/rancher
    release_namespace: cattle-system
    create_namespace: true
    wait: true
    values:
      hostname: "{{ rancher_dns_name }}"
      replicas: "{{ rancher_replicas }}"
    state: present
